In [3]:
import pandas as pd
import numpy
import matplotlib.pyplot as plt

df = pd.read_csv("../data/processed/Chocolate_Sales_Curated.csv")

In [5]:
df["date"] = pd.to_datetime(df["date"], errors='coerce')
df["month"] = df["date"].dt.month
df["day_of_week"] = df["date"].dt.dayofweek
df

,sales_person,country,product,date,amount,boxes_shipped,month,day_of_week
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.00,180,1,1
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.00,94,8,0
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.00,91,7,3
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.00,342,4,2
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.00,184,2,3
...,...,...,...,...,...,...,...,...
3277,Karlen McCaffrey,Australia,Spicy Special Slims,2024-05-17,5303.58,354,5,4
3278,Jehu Rudeforth,USA,White Choc,2024-06-07,7339.32,121,6,4
3279,Ches Bonnell,Canada,Organic Choco Syrup,2024-07-26,616.09,238,7,4
3280,Dotty Strutley,India,Eclairs,2024-07-28,2504.62,397,7,6
3281,Karlen McCaffrey,India,70% Dark Bites,2024-05-23,5915.87,355,5,3

In [14]:
# Prepare for regression
from sklearn.preprocessing import OneHotEncoder

target = "amount"
inputs = ["boxes_shipped", "country", "product", "sales_person", "month", "day_of_week"]

X = df[inputs]
y = df[target]

categorical_cols = ["country", "product", "sales_person"]
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

# Fit și transform
encoded = encoder.fit_transform(X[categorical_cols])
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(categorical_cols))

numeric_cols = ["boxes_shipped", "month", "day_of_week"]
X_encoded = pd.concat([X[numeric_cols].reset_index(drop=True), encoded_df], axis=1)

In [18]:
X_encoded

,boxes_shipped,month,day_of_week,country_Australia,country_Canada,country_India,country_New Zealand,country_UK,country_USA,product_50% Dark Bites,...,sales_person_Karlen McCaffrey,sales_person_Kelci Walkden,sales_person_Madelene Upcott,sales_person_Mallorie Waber,sales_person_Marney O'Breen,sales_person_Oby Sorrel,sales_person_Rafaelita Blaksland,sales_person_Roddy Speechley,sales_person_Van Tuxwell,sales_person_Wilone O'Kielt
0,180,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,94,8,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,91,7,3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,342,4,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,184,2,3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3277,354,5,4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3278,121,6,4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3279,238,7,4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3280,397,7,6,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3281,355,5,3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
# Saving the processed output
X_encoded.to_csv("../data/processed/X_encoded.csv", index=False)